FROM maven:3.9-eclipse-temurin-21-alpine AS build-env

WORKDIR /app

COPY pom.xml ./
RUN mvn dependency:go-offline --batch-mode

COPY src ./src
RUN mvn clean package --batch-mode -DskipTests

FROM eclipse-temurin:21-jre-alpine

WORKDIR /app

COPY --from=build-env /app/target/demo-0.0.1-SNAPSHOT.jar ./app.jar

EXPOSE 8082

ENTRYPOINT ["java", "-jar", "app.jar"]
